#!/bin/bash
#exit-options-manager

#define some variables
TITLE="$(gettext 'Exit-options-manager')"
CLASS="eom"
ICONPATH="/usr/share/pixmaps/exit-options-manager.svg"

# buttons
export BTN_ABOUT=$(gettext "About")  ; BTN_ABOUT+='!help-about'
export BTN_CLOSE=$(gettext "Close")  ; BTN_CLOSE+='!window-close'
export BTN_HELP=$(gettext "Help")    ; BTN_HELP+='!help-contents'
export BTN_OK=$(gettext "OK")        ; BTN_OK+='!object-select'
export BTN_APPLY=$(gettext "Apply")        ; BTN_OK+='!object-select'

###Get list of themes###

ICONSETLIST=$(ls -f usr/share/exit-options/conf/configs_alt/*.conf )

ICONSETARRAY=($ICONSETLIST)

for i in "${ICONSETARRAY[@]}"
do
   i=$(basename $i)
done


###read current config settings###

source $HOME/.config/MX-Linux/exit-options.conf

if [ -z "$timeout" ]; then
    timeout=10
fi

if [ -z "$layout" ]; then
    layout=horizontal
fi

if [ "$layout" = horizontal ]; then
    LAYOUTOTHER=vertical
elif [ "$layout" = vertical ]; then
    LAYOUTOTHER=horizontal
fi

if [ -z "$Margin" ]; then
    Margin=6
fi

if [ -z "$Spacing" ]; then
    Spacing=12
fi

if [ -z "$IconSize" ]; then
    IconSize=64
fi

######################################################
###Get images###

split_arg () {
 echo -e "\f"
 echo "$6"
}
export -f split_arg

export fpipe="$(mktemp -u --tmpdir fvwmei.XXXXXXXX)"
mkfifo "$fpipe"
trap "rm "$fpipe"" EXIT
exec 3<> "$fpipe"


########
#length=${#ICONSETARRAY[@]}

for i in "${ICONSETARRAY[@]}"
do
   ICONIMAGEADD=$(echo "false $i \"/user/share/exit-options/$i/icons/screenshot.png\" \\")

   ICONIMAGE=$(echo -e "$ICONIMAGEADD \n$ICONIMAGE")
   
done

##########

#    false $ICONSET "/user/share/exit-options/$ICONSET/icons/screenshot.png" \

yad --plug=$fkey --tabnum=1 \
    --select-action='bash -c "split_arg %s >$fpipe"' \
    --hide-column=6 \
    --list --checklist \
    --width=900 --height=650 \
    --column=Iconset --column="" \
    $ICONIMAGE
    >$ICONSET &
    
yad --plug=$fkey --tabnum=2 --list --no-headers --listen --cycle-read --column=":IMG" <&3  &

yad --paned --key=$fkey --title="Extension Installer" \
    --center --orient=Horizontal --splitter=500 --width=800 --height=600
    
exec 3>&-


############################################


###MAIN###

fkey=5678

yad --plug="$fkey" --tabnum=1 --list --no-headers \
--column=Style --text-align=left --separator="" \
< $ICONSETLIST > $ICONSET &


yad --plug="$fkey" --tabnum=3 --form --text-align=left --separator="" \
--field="$(gettext 'Layout')":CB "$layout!$LAYOUTOTHER" \
--field="$(gettext 'Timeout')":NUM "$timeout\!1..60\!1\!0" \
--field="$(gettext 'Icon Size')":NUM "$IconSize\!32..128\!32\!0" \
--field="$(gettext 'Margin')":NUM "$Margin\!0..64\!1\!0" \
--field="$(gettext 'Spacing')":NUM "$Spacing\!0..64\!1\!0" \
--field=" ":LBL " " \
> $YADSETTINGS &



TEXT1="$(gettext 'Select icon set and settings for exit-options')"

yad --paned --key="$fkey" --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" \
--text="$TEXT1\n$TEXT2\n" --width=600 --height=400 --borders=20 --center --fixed \
--button="${BTN_CLOSE}":4 --button="${BTN_APPLY}":3


RET=$?
    (( RET != 3 )) && exit


eval TAB1=($(< $ICONSET))
eval TAB2=($(< $YADSETTINGS))


###Apply Theme###

cp $TAB1 $HOME/.config/MX-Linux/exit-options.conf


###Apply Settings###

OLDLAYOUT="$(grep 'layout=' $HOME/.config/MX-Linux/exit-options.conf  | sed -e "s/layout=//")"
OLDTIMEOUT="$(grep 'timeout=' $HOME/.config/MX-Linux/exit-options.conf  | sed -e "s/timeout=//")"
OLDICONSIZE="$(grep 'IconSize=' $HOME/.config/MX-Linux/exit-options.conf  | sed -e "s/IconSize=//")"
OLDMARGIN="$(grep 'Margin=' $HOME/.config/MX-Linux/exit-options.conf  | sed -e "s/Margin=//")"
OLDSPACING="$(grep 'Spacing=' $HOME/.config/MX-Linux/exit-options.conf  | sed -e "s/Spacing=//")"

NEWLAYOUT="${TAB2[0]}"
NEWTIMEOUT="${TAB2[1]}"
NEWICONSIZE="${TAB2[2]}"
NEWMARGIN="${TAB2[3]}"
NEWSPACING="${TAB2[4]}"


if [ "$NEWLAYOUT" != "$OLDLAYOUT" ]; then
    sed -i "s/${OLDLAYOUT}/${NEWLAYOUT}/" $HOME/.config/MX-Linux/exit-options.conf
fi

if [ "$NEWTIMEOUT" != "$OLDTIMEOUT" ]; then
    sed -i "s/${OLDTIMEOUT}/${NEWTIMEOUT}/" $HOME/.config/MX-Linux/exit-options.conf
fi

if [ "$NEWICONSIZE" != "$OLDICONSIZE" ]; then
    sed -i "s/${OLDICONSIZE}/${NEWICONSIZE}/" $HOME/.config/MX-Linux/exit-options.conf
fi

if [ "$NEWMARGIN" != "$OLDMARGIN" ]; then
    sed -i "s/${OLDMARGIN}/${NEWMARGIN}/" $HOME/.config/MX-Linux/exit-options.conf
fi

if [ "$NEWSPACING" != "$OLDSPACING" ]; then
    sed -i "s/${OLDSPACING}/${NEWSPACING}/" $HOME/.config/MX-Linux/exit-options.conf
fi


TEXTDONE1="$(eval_gettext 'All done!')"
TEXTDONE2="$(eval_gettext 'Changes to exit-options settings applied.')"

	yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" \
	--width=400 --height=200 --fixed --center --borders=20 \
	--text="$TEXTDONE1\n$TEXTDONE2\n" --text-align=center --button="${BTN_OK}" \


exit
